In [1]:
# !ln -s /kaggle/input/dlsprint2/badlad/images /kaggle/working/datasets/badlad/images
# !ln -s /kaggle/input/dlsprint2/badlad/labels/yolov8_format/train /kaggle/working/datasets/badlad/labels

In [2]:
# import os
# from tqdm import tqdm

# def all_files_in_folder_symlink(source_dir, target_dir):
#     files = os.listdir(source_dir)

#     for file in tqdm(files):
#         source_file = os.path.join(source_dir, file)
#         target_file = os.path.join(target_dir, file)
#         os.symlink(source_file, target_file)

    

In [3]:
# all_files_in_folder_symlink("/media/sayan/hdd1/CV/bangla_layout_understanding/yolov8/dataset/labels/training/","/kaggle/working/datasets/badlad/labels/train")

In [4]:
# all_files_in_folder_symlink("/media/sayan/hdd1/CV/bangla_layout_understanding/yolov8/dataset/labels/training/","/kaggle/working/datasets/badlad/images/train")


In [5]:
# all_files_in_folder_symlink("/kaggle/input/dlsprint2/badlad/images/test","/kaggle/working/datasets/badlad/images/test")


In [6]:
# !tree -d

In [13]:
# !pip install ultralytics -q
# !pip install wandb

In [14]:
file_content = """
path: /media/sayan/hdd1/CV/yolov8/dataset # dataset root dir
train: images/training  # train images (relative to 'path') 128 images
val: images/validation  # val images (relative to 'path') 128 images
test:  images/validation

nc: 4

# Classes
names:
  0: paragraph
  1: text_box
  2: image
  3: table

"""

with open("data/yolov8.yaml", mode="w") as f:
    f.write(file_content)

In [15]:
import wandb
wandb.init(mode="disabled")

In [16]:
from ultralytics import YOLO
# from ultralytics.yolo.engine.model import YOLO

model = YOLO("yolov8m-seg.pt")
model.train(data="data/yolov8.yaml", epochs=500, imgsz=1024, batch=6)

Ultralytics YOLOv8.0.131 🚀 Python-3.8.17 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24248MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
yolo/engine/trainer: task=segment, mode=train, model=yolov8m-seg.pt, data=data/yolov8.yaml, epochs=500, patience=50, batch=6, imgsz=1024, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, bo

KeyboardInterrupt: 

In [23]:
# from ultralytics import YOLO
from ultralytics.yolo.engine.model import YOLO
# Load a model
# model = YOLO('config/yolov8.yaml')  # build a new model from scratch
model = YOLO('./runs/segment/train5/weights/best.pt')  # load a pretrained model (recommended for training)

# Use the model
# results = model.train(data='coco128.yaml', epochs=3)  # train the model
# results = model.eval()  # evaluate model performance on the validation set
results = model('/media/sayan/hdd1/CV/bangla_layout_understanding/yolov8/dataset/images/validation/0a90eca6-0138-4bb8-8376-2050d294e8ad.png')  # predict on an image

Ultralytics YOLOv8.0.28 🚀 Python-3.8.17 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24248MiB)
YOLOv8m-seg summary (fused): 245 layers, 27224700 parameters, 0 gradients, 110.0 GFLOPs

image 1/1 /media/sayan/hdd1/CV/bangla_layout_understanding/yolov8/dataset/images/validation/0a90eca6-0138-4bb8-8376-2050d294e8ad.png: 1024x736 29 paragraphs, 32 text_boxs, 16.2ms
Speed: 0.3ms pre-process, 16.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)


In [24]:
results

[Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks
 type: <class 'torch.Tensor'>
 shape: torch.Size([61, 6])
 dtype: torch.float32
  + tensor([[3.50000e+01, 2.02000e+02, 6.29000e+02, 3.02000e+02, 8.10269e-01, 0.00000e+00],
         [3.70000e+01, 1.58000e+02, 6.45000e+02, 1.94000e+02, 6.13874e-01, 0.00000e+00],
         [3.70000e+01, 1.25000e+02, 2.69000e+02, 1.46000e+02, 5.91340e-01, 1.00000e+00],
         [4.00000e+01, 6.68000e+02, 2.01000e+02, 6.87000e+02, 5.75519e-01, 1.00000e+00],
         [1.36000e+02, 4.23000e+02, 6.26000e+02, 4.84000e+02, 5.64348e-01, 0.00000e+00],
         [1.32000e+02, 4.87000e+02, 6.27000e+02, 5.26000e+02, 5.38116e-01, 0.00000e+00],
         [8.90000e+01, 3.68000e+02, 1.07000e+02, 3.80000e+02, 5.38042e-01, 1.00000e+00],
         [1.36000e+02, 3.77000e+02, 6.25000e+02, 4.27000e+02, 5.31771e-01, 0.00000e+00],
         [4.30000e+01, 9.30000e+02, 6.40000e+01, 9.41000e+02, 5.24673e-01, 1.00000e+00],
         [4.30000e+01, 7.53000e+02, 5.70000e

In [29]:
results[0].Masks.masks

AttributeError: 
            'Results' object has no attribute 'Masks'. Valid 'Results' object attributes and properties are:

            Attributes:
                boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
                masks (Masks, optional): A Masks object containing the detection masks.
                probs (torch.Tensor, optional): A tensor containing the detection class probabilities.
                orig_shape (tuple, optional): Original image size.
            

In [25]:
results[0].boxes.xyxy

tensor([[ 35., 202., 629., 302.],
        [ 37., 158., 645., 194.],
        [ 37., 125., 269., 146.],
        [ 40., 668., 201., 687.],
        [136., 423., 626., 484.],
        [132., 487., 627., 526.],
        [ 89., 368., 107., 380.],
        [136., 377., 625., 427.],
        [ 43., 930.,  64., 941.],
        [ 43., 753.,  57., 764.],
        [ 86., 317., 108., 332.],
        [ 90., 352., 108., 363.],
        [ 44., 737.,  61., 748.],
        [ 42., 946.,  63., 957.],
        [ 89., 384., 108., 396.],
        [255.,  44., 407.,  93.],
        [479., 122., 601., 140.],
        [ 43., 720.,  59., 731.],
        [ 88., 400., 109., 413.],
        [ 88., 336., 108., 347.],
        [495., 617., 582., 667.],
        [ 42., 849.,  65., 861.],
        [ 43., 768.,  59., 780.],
        [256.,  91., 409., 114.],
        [140., 327., 626., 361.],
        [ 42., 912.,  64., 926.],
        [ 42., 703.,  59., 716.],
        [ 88., 558., 113., 572.],
        [254.,  45., 408., 113.],
        [143.,

In [26]:
results[0].boxes.conf

tensor([0.81027, 0.61387, 0.59134, 0.57552, 0.56435, 0.53812, 0.53804, 0.53177, 0.52467, 0.51449, 0.49252, 0.48943, 0.48115, 0.46967, 0.46298, 0.46294, 0.45814, 0.45744, 0.45685, 0.45047, 0.44319, 0.43996, 0.42676, 0.42469, 0.42291, 0.40941, 0.40275, 0.39225, 0.38419, 0.38000, 0.37505, 0.36713, 0.36586, 0.36503,
        0.36247, 0.35989, 0.35982, 0.35973, 0.35845, 0.35636, 0.34524, 0.32289, 0.32230, 0.32164, 0.31795, 0.31007, 0.30835, 0.30729, 0.30331, 0.29981, 0.29897, 0.29264, 0.29216, 0.29131, 0.27698, 0.27531, 0.27136, 0.26884, 0.26059, 0.25477, 0.25460], device='cuda:0')

In [27]:
results[0].boxes.cls

tensor([0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.], device='cuda:0')